import Form from "../models/Form.js";
import ragService from "../services/ragService.js";
import fs from "fs";
import csv from "csv-parser";

async function processFile(filePath, mimeType) {
    const results = [];
    return new Promise((resolve, reject) => {
        if (mimeType === "application/json") {
            fs.readFile(filePath, "utf8", (err, data) => {
                if (err) reject(err);
                try {
                    const jsonData = JSON.parse(data);
                    if (Array.isArray(jsonData)) {
                        // Assume array of objects
                        jsonData.forEach(item => results.push(item));
                    } else {
                        results.push(jsonData);
                    }
                    resolve(results);
                } catch (e) {
                    reject(e);
                }
            });
        } else {
            // Assume CSV
            fs.createReadStream(filePath)
                .pipe(csv())
                .on("data", (data) => results.push(data))
                .on("end", () => resolve(results))
                .on("error", (error) => reject(error));
        }
    });
}

async function uploadData(req, res) {
    try {
        const { id } = req.params;
        const file = req.file;

        if (!file) {
            return res.status(400).json({ error: "No file uploaded" });
        }

        const data = await processFile(file.path, file.mimetype);

        // Generate embeddings for new data
        const newResponses = await Promise.all(
            data.map(async (item) => ({
                mode: "plaintext",
                data: item,
                embedding: await ragService.generateEmbedding(JSON.stringify(item)),
                schemaVersionUsed: 1,
            }))
        );

        const form = await Form.findById(id);
        if (!form) {
            // Cleanup file
            fs.unlinkSync(file.path);
            return res.status(404).json({ error: "Form not found" });
        }

        const schemaVersionUsed = form.schemaVersion ?? 1;
        newResponses.forEach((r) => {
            r.schemaVersionUsed = schemaVersionUsed;
        });

        form.responses.push(...newResponses);
        await form.save();

        // Index new responses in ChromaDB
        // We need the _id generated by Mongo, so we save first then iterate
        // The 'newResponses' array doesn't have _ids until save? 
        // Mongoose assigns _ids when we push if we use subdocs, but let's grab them from the saved form.

        // Actually, let's look at the tail of the responses array
        const addedResponses = form.responses.slice(-newResponses.length);

        await Promise.all(addedResponses.map(async (response) => {
            // response.data is the plaintext data from CSV
            await ragService.addResponse(
                id,
                response._id.toString(),
                response.embedding,
                { mode: "plaintext", data: response.data }
            );
        }));

        // Cleanup file
        fs.unlinkSync(file.path);

        res.json({ message: "Data uploaded successfully", count: newResponses.length });
    } catch (error) {
        console.error("Upload error:", error);
        if (req.file) fs.unlinkSync(req.file.path); // Cleanup
        res.status(500).json({ error: error.message });
    }
}

export default {
    uploadData,
};
